name: onboarding_app
description: A Flutter onboarding app with language selection

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Aeonik
      fonts:
        - asset: fonts/AeonikTRIAL-Light.otf
          weight: 300
        - asset: fonts/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: fonts/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: fonts/AeonikTRIAL-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/AeonikTRIAL-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/AeonikTRIAL-BoldItalic.otf
          weight: 700
          style: italic

  assets:
    - assets/images/